name: Deploy to cPanel bare repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.CPANEL_HOST }}" >> ~/.ssh/known_hosts

      - name: Start SSH agent with private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CPANEL_SSH_KEY }}

      - name: Push to cPanel bare repo (triggers post-receive)
        run: |
          git remote add cpanel "ssh://${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }}:22/~/repos/kanavana-pilot.git" || true
          git push cpanel main
