name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent with private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CPANEL_SSH_KEY }}

      - name: Push to cPanel bare repo
        env:
          GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
        run: |
          git remote add cpanel "ssh://${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }}:22/~/repos/kanavana-pilot.git" \
            || git remote set-url cpanel "ssh://${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }}:22/~/repos/kanavana-pilot.git"
          git push cpanel main
